# Based on .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  # Decompress test data
  - sudo apt-get install p7zip
  - cd test-data
  # Save folder with test data i an environment variable
  - export IMNR_TEST_DATA=`pwd`
  - 7z e test-data.7z
  - cd ..
  # Goto the the package folder
  - cd imgnoiser
  # Continue as normal
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh r_binary_install ggplot2
  - ./travis-tool.sh install_github hadley/dplyr
  - ./travis-tool.sh install_github wch/R6
  - ./travis-tool.sh install_github hadley/lazyeval
  - ./travis-tool.sh install_github Rdatatable/data.table
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - BOOTSTRAP_LATEX=1 _R_CHECK_FORCE_SUGGESTS_=0 R_CHECK_ARGS="--as-cran"
